version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile_production
      context: .
      args:
        - enable_mecab=1
    volumes:
      - './config.json:/nullcat-chan/config.json:ro'
      - './font.ttf:/nullcat-chan/font.ttf:ro'
      - './data:/nullcat-chan/data'
    restart: always
    environment:
      TZ: Asia/Tokyo
